name: Caller 1

on:
  push:
    branches: [ main ]

jobs:
  plan:
    uses: rara-tan/zenn-githubactions-reuse-workflow/.github/workflows/common.yml@main
    with:
      input-a: a
      input-b: b
    secrets:
      secret-value: secret!
